### ISSUE TITLE
[enhancement] Decomposing Unicode input to NFD prior to rendering

### ISSUE THREAD

**Issue by mxfh** [hrqr/hrqr.github.io#1]
Would normalizing Unicode input to its decomposed forms, if found in the letterdatabase mess with the encoded content?

The database might be even more versatile as a collection of NFD codepoints applied to [decomposed characters](https://en.wikipedia.org/wiki/Unicode_equivalence#Example)

This could be done with http://git.io/unorm or [ES6 in supported Browsers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize)

**Comment by vheun** [comment]
Thats a good point. But I like that a human can just read through the alphabet. That makes it easier to edit. I will try experiments in taking more care of encoding everything in to utf-8 on the webpage and also  in the c++ code. If that does not help, some other ideas need to be considered. 

I think that the c++ code character encoding is the problem, not so much this webpage.
